### ISSUE TITLE
🐛 Circular dependency error (Player.py and utils.py)

### ISSUE THREAD

**Issue by sjalkote** [TechnoShip123/numbersense#8]
There is currently a circular dependency error present in `Player.py` and `utils.py` which can be resolved by moving around functions to better locations.

Tied into the fix for this issue should also be a fix to the following error that appears in some cases:
```
Traceback (most recent call last):
  File "numbersense/./main.py", line 3, in <module>
    print(utils.create_default("amogus"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numbersense/utils.py", line 511, in create_default
    Player(username, QuizType.EASY, password="password")
  File "numbersense/Player.py", line 101, in __init__
    self.password: str = utils.encrypt_password(password, True)  # Hashed password as str
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numbersense/utils.py", line 435, in encrypt_password
    hashed_pwd = bcrypt.hashpw(bytes, bcrypt.gensalt())  # Newly hashed & salted password
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: hashpw() argument 1 must be str, not bytes

Process finished with exit code 1
```

**Comment by sjalkote** [comment]
Fixed in 08352c8
